version: "3"
services:
  selenium:
    image: selenium/standalone-firefox:latest
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=10
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444"]

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - HEADLESS=true
      - DEBUG=false
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - selenium

    healthcheck:
      test: ["CMD", "curl", "-f", "http://selenium:4444"]
      interval: 30s
  worker:
    build: ./app
    command: sh -c "celery -A worker.celery_app worker --loglevel=info --concurrency=10"
    volumes:
      - ./app:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  dashboard:
    build: ./app
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - "5556:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - redis
      - worker
networks:
    default:
